apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: task-events-subscription
spec:
  topic: task-events
  routes:
    default: /api/events/task-completed
  pubsubname: todo-pubsub
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: notifications-subscription
spec:
  topic: notifications
  routes:
    default: /api/events/notifications
  pubsubname: todo-pubsub
